matrix:
  include:
    - os: osx
      osx_image: xcode10.2

script:
- cd URITemplate && swift package generate-xcodeproj
- xcodebuild -project Mockingjay.xcodeproj -scheme Mockingjay test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --quick
